---
collections:
  - name: ansible.windows
    version: 1.9.0
  - name: chocolatey.chocolatey
    version: 1.2.0
  - name: community.general
    version: 4.4.0
  - name: community.vmware
    version: 1.17.0
  - name: community.windows
    version: 1.9.0
  - name: servicenow.servicenow
    version: 1.0.6
  - name: cyberark.pas
    version: 1.0.14
  - name: cyberark.conjur
    version: 1.2.0
  - name: servicenow.itsm
    version: 2.2.0
